theme: jekyll-theme-minimal
title: "CMSE 495"
description: "Michigan State University Data Science Capstone." 
logo: /assets/img/logo.png
url: https://msu-cmse-courses.github.io/cmse495-SS24/
permalink: /:year/:month/:day/:title
