theme: jekyll-theme-minimal
title: "CMSE 495"
description: "This is the webpage for CMSE495 Data Science Capstone Course. These materials are provided as an Open Educational Resource (OER).  Instructors interested in using these classroom resources should reach out to Dirk Colbry (colbrydi@msu.edu) who can provide all the materials and instructor notes."
logo: /assets/img/logo.png
